version: "3"

services:
  frontend:
    tty: true
    stdin_open: true
    build: ./Frontend
    container_name: eco-frontend-container
    volumes:
      - ./Frontend/src:/app/src:ro
    ports:
      - "3030:3000"
    environment:
      - WATCHPACK_POLLING=true #Necesario para usuarios con windows
    networks:
      docnet:
        ipv4_address: 10.10.10.4

  backend:
    build: ./Backend/API
    container_name: python-api-container
    volumes:
      - ./Backend/API:/API:ro
    ports:
      - "4040:4040"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DB_NAME=${MYSQL_DATABASE_NAME}
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DB_USERNAME=root
      - DB_HOST=database
    depends_on:
      - database
    networks:
      docnet:
        ipv4_address: 10.10.10.5

  database:
    build: ./Backend/DB
    container_name: db-api-container
    volumes:
      - ./Backend/DB/mysql:/var/lib/mysql:rw
      - ./Backend/DB/backup.sql:/docker-entrypoint-initdb.d/backup.sql:ro
    ports:
      - "6060:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    networks:
      docnet:
        ipv4_address: 10.10.10.7

networks:
  docnet:
    ipam:
      config:
        - subnet: 10.10.10.0/24