/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/AlletraCity.glb 
*/

import React, { useLayoutEffect, useRef } from 'react'
import { useGLTF, useScroll } from '@react-three/drei'
import gsap from 'gsap';
import { useFrame } from '@react-three/fiber';

export function AlletraCity(props) {
  const { nodes, materials } = useGLTF('./models/AlletraCity.glb');

  const FLOOR_HEIGHT = 5.0;
  const NB_FLOORS = 3;

  const ref = useRef();
  const tl = useRef();

  const scroll = useScroll();

  useFrame(() => {
    tl.current.seek(scroll.offset * tl.current.duration());
  });

  useLayoutEffect(() => {
    tl.current = gsap.timeline();

    // rotation
    tl.current.to(
      ref.current.rotation,
      {
        duration: 3,
        y: -Math.PI,
      },
      0,
    );

    // position 1
    tl.current.to(
      ref.current.position,
      {
        duration: 1.5,
        y: -FLOOR_HEIGHT * (NB_FLOORS - 1),
        x: -60,
        z: 60
      },
      0,
    );

    // position 2
    tl.current.to(
      ref.current.position,
      {
        duration: 1.3,
        y: -FLOOR_HEIGHT * (NB_FLOORS - 1),
        x: 80,
        z: -1
      },
      1.5,
    );
  }, []);

  return (
    <group {...props} dispose={null} ref={ref} position={[80, 0, -2]}>
      <mesh geometry={nodes.tokyo_tower_town_working.geometry} material={materials.palette} />
    </group>
  )
}

useGLTF.preload('./models/AlletraCity.glb')
