/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/rocket.glb 
*/

import React, { useLayoutEffect, useRef } from "react";
import { useGLTF, useScroll } from "@react-three/drei";
import gsap from "gsap";
import { useFrame } from "@react-three/fiber";

export function ApolloHeights(props) {
  const { nodes, materials } = useGLTF("./models/ApolloHeights.glb");

  const FLOOR_HEIGHT = 0.6;
  const NB_FLOORS = 3;

  const ref = useRef();
  const tl = useRef();

  const scroll = useScroll();

  useFrame(() => {
    tl.current.seek(scroll.offset * tl.current.duration());
  });

  useLayoutEffect(() => {
    tl.current = gsap.timeline();

    // position 0
    tl.current.to(
      ref.current.rotation,
      {
        duration: 3.5,
        y: -Math.PI,
      },
      0,
    );

    // position 1
    tl.current.to(
      ref.current.position,
      {
        duration: 1,
        y: -FLOOR_HEIGHT * (NB_FLOORS - 1),
        x: -1,
        z: 2
      },
      0,
    );

    // position 2
    tl.current.to(
      ref.current.position,
      {
        duration: 1,
        y: -FLOOR_HEIGHT * (NB_FLOORS - 1),
        x: 2,
        z: -3
      },
      1.5,
    );

  }, []);

  return (
    <group {...props} dispose={null} ref={ref} position={[1, 0, -2]}>
      <mesh
        geometry={nodes.group344410003.geometry}
        material={materials.mat10}
      />
      <mesh
        geometry={nodes.group48642844.geometry}
        material={materials.mat10}
      />
      <mesh
        geometry={nodes.group709040070.geometry}
        material={materials.mat10}
      />
      <mesh
        geometry={nodes.group1225221972.geometry}
        material={materials.mat10}
      />
      <mesh
        geometry={nodes.group966288980.geometry}
        material={materials.mat10}
      />
      <mesh
        geometry={nodes.group1710198644.geometry}
        material={materials.mat10}
      />
      <mesh
        geometry={nodes.group1364174740.geometry}
        material={materials.mat10}
      />
      <mesh
        geometry={nodes.group458531781.geometry}
        material={materials.mat10}
      />
      <mesh
        geometry={nodes.group906924465.geometry}
        material={materials.mat10}
      />
      <mesh
        geometry={nodes.group1299656231.geometry}
        material={materials.mat10}
      />
      <mesh
        geometry={nodes.group313313379.geometry}
        material={materials.mat10}
      />
      <mesh
        geometry={nodes.group1105021096.geometry}
        material={materials.mat16}
      />
      <mesh
        geometry={nodes.group1019848082.geometry}
        material={materials.mat16}
      />
      <mesh
        geometry={nodes.group955469005.geometry}
        material={materials.mat16}
      />
      <mesh
        geometry={nodes.group16455425.geometry}
        material={materials.mat16}
      />
      <mesh
        geometry={nodes.group772642287.geometry}
        material={materials.mat16}
      />
      <mesh
        geometry={nodes.group1544424443.geometry}
        material={materials.mat16}
      />
      <mesh
        geometry={nodes.group1234334590.geometry}
        material={materials.mat16}
      />
      <mesh
        geometry={nodes.group1947661243.geometry}
        material={materials.mat16}
      />
      <mesh
        geometry={nodes.group568307849.geometry}
        material={materials.mat16}
      />
      <mesh
        geometry={nodes.group1927329311.geometry}
        material={materials.mat16}
      />
      <mesh
        geometry={nodes.group623023814.geometry}
        material={materials.mat16}
      />
      <mesh
        geometry={nodes.group1389993512.geometry}
        material={materials.mat16}
      />
      <mesh
        geometry={nodes.group1829196498.geometry}
        material={materials.mat21}
      />
      <mesh
        geometry={nodes.group611393218.geometry}
        material={materials.mat21}
      />
      <mesh
        geometry={nodes.group1630261228.geometry}
        material={materials.mat21}
      />
      <mesh
        geometry={nodes.group207175009.geometry}
        material={materials.mat21}
      />
      <mesh
        geometry={nodes.group1173098109.geometry}
        material={materials.mat21}
      />
      <mesh
        geometry={nodes.group1591568081.geometry}
        material={materials.mat21}
      />
      <mesh
        geometry={nodes.group564080171.geometry}
        material={materials.mat21}
      />
      <mesh
        geometry={nodes.group1306580883.geometry}
        material={materials.mat21}
      />
      <mesh
        geometry={nodes.group814783659.geometry}
        material={materials.mat21}
      />
      <mesh
        geometry={nodes.group993367364.geometry}
        material={materials.mat21}
      />
      <mesh
        geometry={nodes.group1128458493.geometry}
        material={materials.mat21}
      />
      <mesh
        geometry={nodes.group964273475.geometry}
        material={materials.mat21}
      />
      <mesh
        geometry={nodes.group558215421.geometry}
        material={materials.mat21}
      />
      <mesh
        geometry={nodes.group1093621713.geometry}
        material={materials.mat21}
      />
      <mesh
        geometry={nodes.group234711545.geometry}
        material={materials.mat21}
      />
      <mesh
        geometry={nodes.group2085148819.geometry}
        material={materials.mat21}
      />
      <mesh
        geometry={nodes.group807470519.geometry}
        material={materials.mat21}
      />
      <mesh geometry={nodes.group4977370.geometry} material={materials.mat21} />
      <mesh
        geometry={nodes.group427639871.geometry}
        material={materials.mat21}
      />
      <mesh
        geometry={nodes.group1316127002.geometry}
        material={materials.mat16}
      />
      <mesh
        geometry={nodes.group480874371.geometry}
        material={materials.mat16}
      />
      <mesh
        geometry={nodes.group844888821.geometry}
        material={materials.mat16}
      />
      <mesh
        geometry={nodes.group944269421.geometry}
        material={materials.mat16}
      />
      <mesh
        geometry={nodes.group1666155291.geometry}
        material={materials.mat21}
      />
      <mesh
        geometry={nodes.group1151316916.geometry}
        material={materials.mat21}
      />
      <mesh
        geometry={nodes.group951584146.geometry}
        material={materials.mat21}
      />
      <mesh
        geometry={nodes.group802678147.geometry}
        material={materials.mat10}
      />
      <mesh
        geometry={nodes.group1796579314.geometry}
        material={materials.mat10}
      />
      <mesh
        geometry={nodes.group917501534.geometry}
        material={materials.mat10}
      />
      <mesh
        geometry={nodes.group1206495362.geometry}
        material={materials.mat10}
      />
      <mesh
        geometry={nodes.group815692707.geometry}
        material={materials.mat10}
      />
      <mesh
        geometry={nodes.group1354228285.geometry}
        material={materials.mat10}
      />
      <mesh
        geometry={nodes.group1504391327.geometry}
        material={materials.mat10}
      />
      <mesh
        geometry={nodes.group302536219.geometry}
        material={materials.mat10}
      />
      <mesh
        geometry={nodes.group745254378.geometry}
        material={materials.mat10}
      />
      <mesh
        geometry={nodes.group346366871.geometry}
        material={materials.mat10}
      />
      <mesh
        geometry={nodes.group489607522.geometry}
        material={materials.mat10}
      />
      <mesh
        geometry={nodes.group421203999.geometry}
        material={materials.mat10}
      />
      <mesh
        geometry={nodes.group609771286.geometry}
        material={materials.mat21}
      />
      <mesh
        geometry={nodes.group1967381130.geometry}
        material={materials.mat21}
      />
      <mesh
        geometry={nodes.mesh164032811.geometry}
        material={materials.mat16}
      />
      <mesh
        geometry={nodes.mesh164032811_1.geometry}
        material={materials.mat17}
      />
      <mesh
        geometry={nodes.mesh782243387.geometry}
        material={materials.mat21}
      />
      <mesh
        geometry={nodes.mesh782243387_1.geometry}
        material={materials.mat16}
      />
      <mesh
        geometry={nodes.mesh782243387_2.geometry}
        material={materials.mat15}
      />
      <mesh
        geometry={nodes.mesh782243387_3.geometry}
        material={materials.mat8}
      />
      <mesh
        geometry={nodes.mesh782243387_4.geometry}
        material={materials.mat4}
      />
    </group>
  );
}

useGLTF.preload("./models/ApolloHeights.glb");
