/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/ComposableCloud.glb 
*/

import React, { useLayoutEffect, useRef } from 'react'
import { useGLTF, useScroll } from '@react-three/drei'
import gsap from 'gsap';
import { useFrame } from '@react-three/fiber';

export function ComposableCloudl(props) {
  const { nodes, materials } = useGLTF('./models/ComposableCloud.glb');

  const FLOOR_HEIGHT = 0.4;
  const NB_FLOORS = 3;

  const ref = useRef();
  const tl = useRef();

  const scroll = useScroll();

  useFrame(() => {
    tl.current.seek(scroll.offset * tl.current.duration());
  });

  useLayoutEffect(() => {
    tl.current = gsap.timeline();

    // position 0
    tl.current.to(
      ref.current.rotation,
      {
        duration: 3,
        y: -Math.PI,
      },
      0,
    );

    // position 1
    tl.current.to(
      ref.current.position,
      {
        duration: 1,
        y: -FLOOR_HEIGHT * (NB_FLOORS - 1),
        x: -1,
        z: -0.4
      },
      0,
    );

    // position 2
    tl.current.to(
      ref.current.position,
      {
        duration: 1,
        y: -FLOOR_HEIGHT * (NB_FLOORS - 1),
        x: 1,
        z: -0.5
      },
      1.2,
    );
  }, []);

  return (
    <group {...props} dispose={null} ref={ref} position={[1, 0, -0.3]}>
      <mesh geometry={nodes.group1872301862.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group887585770.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group1785927534.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group196205961.geometry} material={materials.mat10} />
      <mesh geometry={nodes.group63162466.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group593424478.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1521073103.geometry} material={materials.mat10} />
      <mesh geometry={nodes.group1082151471.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group333306986.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group276154815.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group823902150.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group247809785.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh1219000781.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh1219000781_1.geometry} material={materials.mat9} />
      <mesh geometry={nodes.mesh1881962715.geometry} material={materials.mat9} />
      <mesh geometry={nodes.mesh1881962715_1.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh1494337977.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh1494337977_1.geometry} material={materials.mat9} />
      <mesh geometry={nodes.mesh246221976.geometry} material={materials.mat9} />
      <mesh geometry={nodes.mesh246221976_1.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh67057303.geometry} material={materials.mat13} />
      <mesh geometry={nodes.mesh67057303_1.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh421901013.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh421901013_1.geometry} material={materials.mat13} />
      <mesh geometry={nodes.mesh486680727.geometry} material={materials.mat14} />
      <mesh geometry={nodes.mesh486680727_1.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh1116972474.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh1116972474_1.geometry} material={materials.mat14} />
      <mesh geometry={nodes.mesh1316379626.geometry} material={materials.mat13} />
      <mesh geometry={nodes.mesh1316379626_1.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh1382887044.geometry} material={materials.mat14} />
      <mesh geometry={nodes.mesh1382887044_1.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh1536220957.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh1536220957_1.geometry} material={materials.mat14} />
      <mesh geometry={nodes.mesh1699150959.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh1699150959_1.geometry} material={materials.mat9} />
      <mesh geometry={nodes.mesh1597053726.geometry} material={materials.mat9} />
      <mesh geometry={nodes.mesh1597053726_1.geometry} material={materials.mat10} />
      <mesh geometry={nodes.mesh1597053726_2.geometry} material={materials.mat19} />
      <mesh geometry={nodes.mesh434512243.geometry} material={materials.mat19} />
      <mesh geometry={nodes.mesh434512243_1.geometry} material={materials.mat9} />
      <mesh geometry={nodes.mesh434512243_2.geometry} material={materials.mat10} />
      <mesh geometry={nodes.mesh1113446100.geometry} material={materials.mat10} />
      <mesh geometry={nodes.mesh1113446100_1.geometry} material={materials.mat9} />
      <mesh geometry={nodes.mesh1113446100_2.geometry} material={materials.mat19} />
      <mesh geometry={nodes.mesh1264448887.geometry} material={materials.mat14} />
      <mesh geometry={nodes.mesh1264448887_1.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh1264448887_2.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh1264448887_3.geometry} material={materials.mat15} />
      <mesh geometry={nodes.mesh267208336.geometry} material={materials.mat15} />
      <mesh geometry={nodes.mesh267208336_1.geometry} material={materials.mat14} />
      <mesh geometry={nodes.mesh267208336_2.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh267208336_3.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh1160365187.geometry} material={materials.mat15} />
      <mesh geometry={nodes.mesh1160365187_1.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh1160365187_2.geometry} material={materials.mat14} />
      <mesh geometry={nodes.mesh1160365187_3.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh1519197050.geometry} material={materials.mat15} />
      <mesh geometry={nodes.mesh1519197050_1.geometry} material={materials.mat14} />
      <mesh geometry={nodes.mesh1519197050_2.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh1519197050_3.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh1436701444.geometry} material={materials.mat15} />
      <mesh geometry={nodes.mesh1436701444_1.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh1436701444_2.geometry} material={materials.mat14} />
      <mesh geometry={nodes.mesh1436701444_3.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh2062688951.geometry} material={materials.mat15} />
      <mesh geometry={nodes.mesh2062688951_1.geometry} material={materials.mat14} />
      <mesh geometry={nodes.mesh2062688951_2.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh2062688951_3.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh1628444825.geometry} material={materials.mat15} />
      <mesh geometry={nodes.mesh1628444825_1.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh1628444825_2.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh1628444825_3.geometry} material={materials.mat14} />
      <mesh geometry={nodes.mesh946911762.geometry} material={materials.mat15} />
      <mesh geometry={nodes.mesh946911762_1.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh946911762_2.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh946911762_3.geometry} material={materials.mat14} />
      <mesh geometry={nodes.mesh1158338487.geometry} material={materials.mat15} />
      <mesh geometry={nodes.mesh1158338487_1.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh1158338487_2.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh1158338487_3.geometry} material={materials.mat14} />
      <mesh geometry={nodes.mesh427715262.geometry} material={materials.mat15} />
      <mesh geometry={nodes.mesh427715262_1.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh427715262_2.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh427715262_3.geometry} material={materials.mat14} />
      <mesh geometry={nodes.mesh1250352314.geometry} material={materials.mat15} />
      <mesh geometry={nodes.mesh1250352314_1.geometry} material={materials.mat14} />
      <mesh geometry={nodes.mesh1250352314_2.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh1250352314_3.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh115179101.geometry} material={materials.mat15} />
      <mesh geometry={nodes.mesh115179101_1.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh115179101_2.geometry} material={materials.mat14} />
      <mesh geometry={nodes.mesh115179101_3.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh1621525122.geometry} material={materials.mat9} />
      <mesh geometry={nodes.mesh1621525122_1.geometry} material={materials.mat10} />
      <mesh geometry={nodes.mesh1621525122_2.geometry} material={materials.mat19} />
      <mesh geometry={nodes.mesh770266912.geometry} material={materials.mat19} />
      <mesh geometry={nodes.mesh770266912_1.geometry} material={materials.mat9} />
      <mesh geometry={nodes.mesh770266912_2.geometry} material={materials.mat10} />
      <mesh geometry={nodes.mesh83140442.geometry} material={materials.mat10} />
      <mesh geometry={nodes.mesh83140442_1.geometry} material={materials.mat9} />
      <mesh geometry={nodes.mesh83140442_2.geometry} material={materials.mat19} />
      <mesh geometry={nodes.mesh365647059.geometry} material={materials.mat19} />
      <mesh geometry={nodes.mesh365647059_1.geometry} material={materials.mat9} />
      <mesh geometry={nodes.mesh365647059_2.geometry} material={materials.mat10} />
      <mesh geometry={nodes.mesh999403242.geometry} material={materials.mat19} />
      <mesh geometry={nodes.mesh999403242_1.geometry} material={materials.mat9} />
      <mesh geometry={nodes.mesh999403242_2.geometry} material={materials.mat10} />
      <mesh geometry={nodes.mesh1504664988.geometry} material={materials.mat19} />
      <mesh geometry={nodes.mesh1504664988_1.geometry} material={materials.mat10} />
      <mesh geometry={nodes.mesh1504664988_2.geometry} material={materials.mat9} />
      <mesh geometry={nodes.mesh1981466897.geometry} material={materials.mat19} />
      <mesh geometry={nodes.mesh1981466897_1.geometry} material={materials.mat9} />
      <mesh geometry={nodes.mesh1981466897_2.geometry} material={materials.mat10} />
      <mesh geometry={nodes.mesh49322897.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh49322897_1.geometry} material={materials.mat14} />
      <mesh geometry={nodes.mesh49322897_2.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh420869121.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh420869121_1.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh420869121_2.geometry} material={materials.mat14} />
      <mesh geometry={nodes.mesh155505903.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh155505903_1.geometry} material={materials.mat11} />
      <mesh geometry={nodes.mesh105770490.geometry} material={materials.mat11} />
      <mesh geometry={nodes.mesh105770490_1.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh455369100.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh455369100_1.geometry} material={materials.mat9} />
      <mesh geometry={nodes.mesh455369100_2.geometry} material={materials.mat15} />
      <mesh geometry={nodes.mesh203304829.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh203304829_1.geometry} material={materials.mat9} />
      <mesh geometry={nodes.mesh758940093.geometry} material={materials.mat9} />
      <mesh geometry={nodes.mesh758940093_1.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh758940093_2.geometry} material={materials.mat15} />
      <mesh geometry={nodes.mesh330781203.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh330781203_1.geometry} material={materials.mat9} />
      <mesh geometry={nodes.mesh960941356.geometry} material={materials.mat9} />
      <mesh geometry={nodes.mesh960941356_1.geometry} material={materials.mat10} />
      <mesh geometry={nodes.mesh960941356_2.geometry} material={materials.mat19} />
      <mesh geometry={nodes.mesh1723174180.geometry} material={materials.mat19} />
      <mesh geometry={nodes.mesh1723174180_1.geometry} material={materials.mat10} />
      <mesh geometry={nodes.mesh1723174180_2.geometry} material={materials.mat9} />
      <mesh geometry={nodes.mesh1658189363.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh1658189363_1.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh537824978.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh537824978_1.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh2130068210.geometry} material={materials.mat15} />
      <mesh geometry={nodes.mesh2130068210_1.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh1348844678.geometry} material={materials.mat10} />
      <mesh geometry={nodes.mesh1348844678_1.geometry} material={materials.mat9} />
      <mesh geometry={nodes.mesh1348844678_2.geometry} material={materials.mat19} />
      <mesh geometry={nodes.mesh1757631645.geometry} material={materials.mat19} />
      <mesh geometry={nodes.mesh1757631645_1.geometry} material={materials.mat10} />
      <mesh geometry={nodes.mesh1757631645_2.geometry} material={materials.mat9} />
      <mesh geometry={nodes.mesh1202162402.geometry} material={materials.mat15} />
      <mesh geometry={nodes.mesh1202162402_1.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh576531375.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh576531375_1.geometry} material={materials.mat15} />
      <mesh geometry={nodes.mesh576531375_2.geometry} material={materials.mat9} />
      <mesh geometry={nodes.mesh570772275.geometry} material={materials.mat13} />
      <mesh geometry={nodes.mesh570772275_1.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh1618802864.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh1618802864_1.geometry} material={materials.mat13} />
      <mesh geometry={nodes.mesh1676309454.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh1676309454_1.geometry} material={materials.mat13} />
      <mesh geometry={nodes.mesh1354328709.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh1354328709_1.geometry} material={materials.mat9} />
    </group>
  )
}

useGLTF.preload('./models/ComposableCloud.glb')
