/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/EzmeralValley.glb 
*/

import React, { useLayoutEffect, useRef } from 'react'
import { useGLTF, useScroll } from '@react-three/drei'
import gsap from 'gsap';
import { useFrame } from '@react-three/fiber';

export function EzmeralValley(props) {
  const { nodes, materials } = useGLTF('./models/EzmeralValley.glb');

  const FLOOR_HEIGHT = 0.3;
  const NB_FLOORS = 3;

  const ref = useRef();
  const tl = useRef();

  const scroll = useScroll();

  useFrame(() => {
    tl.current.seek(scroll.offset * tl.current.duration());
  });

  useLayoutEffect(() => {
    tl.current = gsap.timeline();

    // rotation
    tl.current.to(
      ref.current.rotation,
      {
        duration: 3,
        y: -Math.PI,
      },
      0,
    );

    // position 1
    tl.current.to(
      ref.current.position,
      {
        duration: 1,
        y: -FLOOR_HEIGHT * (NB_FLOORS - 1),
        x: -1,
        z: 2
      },
      0,
    );

    // position 2
    tl.current.to(
      ref.current.position,
      {
        duration: 1.5,
        y: -FLOOR_HEIGHT * (NB_FLOORS - 1),
        x: 2,
        z: -3
      },
      1,
    );
  }, []);
  return (
    <group {...props} dispose={null} ref={ref} position={[1, 0, -2]}>
      <mesh geometry={nodes['Node-Mesh'].geometry} material={materials.mat18} />
      <mesh geometry={nodes['Node-Mesh_1'].geometry} material={materials.mat15} />
      <mesh geometry={nodes['Node-Mesh_2'].geometry} material={materials.mat19} />
      <mesh geometry={nodes['Node-Mesh_3'].geometry} material={materials.mat9} />
      <mesh geometry={nodes['Node-Mesh_4'].geometry} material={materials.mat21} />
      <mesh geometry={nodes['Node-Mesh_5'].geometry} material={materials.mat3} />
      <mesh geometry={nodes['Node-Mesh_6'].geometry} material={materials.mat24} />
      <mesh geometry={nodes['Node-Mesh_7'].geometry} material={materials.mat20} />
      <mesh geometry={nodes['Node-Mesh_8'].geometry} material={materials.mat10} />
      <mesh geometry={nodes['Node-Mesh_9'].geometry} material={materials.mat16} />
      <mesh geometry={nodes['Node-Mesh_10'].geometry} material={materials.mat1} />
      <mesh geometry={nodes['Node-Mesh_11'].geometry} material={materials.mat12} />
      <mesh geometry={nodes['Node-Mesh_12'].geometry} material={materials.mat14} />
    </group>
  )
}

useGLTF.preload('./models/EzmeralValley.glb')
