/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/HPEInnovationHub.glb 
*/

import React, { useLayoutEffect, useRef } from 'react'
import { useGLTF, useScroll } from '@react-three/drei'
import gsap from 'gsap';
import { useFrame } from '@react-three/fiber';

export function HPEInnovationHub(props) {
  const { nodes, materials } = useGLTF('./models/HPEInnovationHub.glb');

  const FLOOR_HEIGHT = 0.2;
  const NB_FLOORS = 3;

  const ref = useRef();
  const tl = useRef();

  const scroll = useScroll();

  useFrame(() => {
    tl.current.seek(scroll.offset * tl.current.duration());
  });

  useLayoutEffect(() => {
    tl.current = gsap.timeline();

    // rotation
    tl.current.to(
      ref.current.rotation,
      {
        duration: 3,
        y: -Math.PI,
      },
      0,
    );

    // position 1
    tl.current.to(
      ref.current.position,
      {
        duration: 1,
        y: -FLOOR_HEIGHT * (NB_FLOORS - 1) -1,
        x: -3,
        z: -1
      },
      0,
    );

    // position 2
    tl.current.to(
      ref.current.position,
      {
        duration: 1,
        y: -FLOOR_HEIGHT * (NB_FLOORS - 1) -1,
        x: -1,
        z: -2.5
      },
      1.5,
    );
  }, []);

  return (
    <group {...props} dispose={null} ref={ref} position={[-1, -1, -2]}>
      <mesh geometry={nodes.group1140946503.geometry} material={materials.mat17} />
      <mesh geometry={nodes.group1942364772.geometry} material={materials.mat22} />
      <mesh geometry={nodes.group564060743.geometry} material={materials.mat17} />
      <mesh geometry={nodes.group1606486772.geometry} material={materials.mat17} />
      <mesh geometry={nodes.group250368908.geometry} material={materials.mat17} />
      <mesh geometry={nodes.group394634144.geometry} material={materials.mat17} />
      <mesh geometry={nodes.group1626028686.geometry} material={materials.mat4} />
      <mesh geometry={nodes.group2132746777.geometry} material={materials.mat4} />
      <mesh geometry={nodes.group537072350.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1604986709.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group158201688.geometry} material={materials.mat4} />
      <mesh geometry={nodes.group308852052.geometry} material={materials.mat4} />
      <mesh geometry={nodes.group1564314892.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group775399069.geometry} material={materials.mat22} />
      <mesh geometry={nodes.group1834308883.geometry} material={materials.mat22} />
      <mesh geometry={nodes.group279731706.geometry} material={materials.mat22} />
      <mesh geometry={nodes.group2077596375.geometry} material={materials.mat22} />
      <mesh geometry={nodes.group1885947375.geometry} material={materials.mat22} />
      <mesh geometry={nodes.group1380893060.geometry} material={materials.mat22} />
      <mesh geometry={nodes.group1955590312.geometry} material={materials.mat22} />
      <mesh geometry={nodes.group2046823740.geometry} material={materials.mat22} />
      <mesh geometry={nodes.group1938308388.geometry} material={materials.mat22} />
      <mesh geometry={nodes.group2139268785.geometry} material={materials.mat22} />
      <mesh geometry={nodes.group873421627.geometry} material={materials.mat22} />
      <mesh geometry={nodes.group1281993969.geometry} material={materials.mat22} />
      <mesh geometry={nodes.group1272602294.geometry} material={materials.mat22} />
      <mesh geometry={nodes.group1962319458.geometry} material={materials.mat22} />
      <mesh geometry={nodes.group46130247.geometry} material={materials.mat22} />
      <mesh geometry={nodes.group331010479.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group2076985631.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group2138588454.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group117260024.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group1416587486.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group542566685.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group960672273.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group626272439.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group1072260926.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group1797940366.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group810465982.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group797661662.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group321321696.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group656191759.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group386737350.geometry} material={materials.mat4} />
      <mesh geometry={nodes.group155209733.geometry} material={materials.mat4} />
      <mesh geometry={nodes.group499374482.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group1748019064.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1413645252.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group496839335.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group952710084.geometry} material={materials.mat17} />
      <mesh geometry={nodes.group429450211.geometry} material={materials.mat17} />
      <mesh geometry={nodes.group1542000236.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group300870941.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group1552731824.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group1469497067.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group877197430.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group450327324.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group529705908.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group1497640686.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group997959245.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group655097576.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group1628975372.geometry} material={materials.mat11} />
      <mesh geometry={nodes.mesh985830789.geometry} material={materials.mat15} />
      <mesh geometry={nodes.mesh985830789_1.geometry} material={materials.mat4} />
      <mesh geometry={nodes.mesh985830789_2.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh1675820717.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh1675820717_1.geometry} material={materials.mat15} />
      <mesh geometry={nodes.mesh1675820717_2.geometry} material={materials.mat4} />
      <mesh geometry={nodes.mesh90543103.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh90543103_1.geometry} material={materials.mat15} />
      <mesh geometry={nodes.mesh90543103_2.geometry} material={materials.mat4} />
      <mesh geometry={nodes.mesh1130891968.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh1130891968_1.geometry} material={materials.mat15} />
      <mesh geometry={nodes.mesh1130891968_2.geometry} material={materials.mat4} />
      <mesh geometry={nodes.mesh141874807.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh141874807_1.geometry} material={materials.mat17} />
      <mesh geometry={nodes.mesh1638011133.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh1638011133_1.geometry} material={materials.mat17} />
      <mesh geometry={nodes.mesh1067756384.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh1067756384_1.geometry} material={materials.mat3} />
      <mesh geometry={nodes.mesh1563131716.geometry} material={materials.mat15} />
      <mesh geometry={nodes.mesh1563131716_1.geometry} material={materials.mat4} />
      <mesh geometry={nodes.mesh1637909053.geometry} material={materials.mat4} />
      <mesh geometry={nodes.mesh1637909053_1.geometry} material={materials.mat15} />
      <mesh geometry={nodes.mesh1088089981.geometry} material={materials.mat3} />
      <mesh geometry={nodes.mesh1088089981_1.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh243407018.geometry} material={materials.mat22} />
      <mesh geometry={nodes.mesh243407018_1.geometry} material={materials.mat10} />
      <mesh geometry={nodes.mesh1949261150.geometry} material={materials.mat10} />
      <mesh geometry={nodes.mesh1949261150_1.geometry} material={materials.mat22} />
      <mesh geometry={nodes.mesh1999338337.geometry} material={materials.mat22} />
      <mesh geometry={nodes.mesh1999338337_1.geometry} material={materials.mat10} />
      <mesh geometry={nodes.mesh1477141948.geometry} material={materials.mat22} />
      <mesh geometry={nodes.mesh1477141948_1.geometry} material={materials.mat10} />
      <mesh geometry={nodes.mesh494719895.geometry} material={materials.mat22} />
      <mesh geometry={nodes.mesh494719895_1.geometry} material={materials.mat10} />
      <mesh geometry={nodes.mesh445860012.geometry} material={materials.mat11} />
      <mesh geometry={nodes.mesh445860012_1.geometry} material={materials.mat10} />
      <mesh geometry={nodes.mesh445860012_2.geometry} material={materials.mat22} />
      <mesh geometry={nodes.mesh486283697.geometry} material={materials.mat11} />
      <mesh geometry={nodes.mesh486283697_1.geometry} material={materials.mat10} />
      <mesh geometry={nodes.mesh486283697_2.geometry} material={materials.mat22} />
      <mesh geometry={nodes.mesh602155895.geometry} material={materials.mat11} />
      <mesh geometry={nodes.mesh602155895_1.geometry} material={materials.mat10} />
      <mesh geometry={nodes.mesh602155895_2.geometry} material={materials.mat22} />
      <mesh geometry={nodes.mesh1306484637.geometry} material={materials.mat11} />
      <mesh geometry={nodes.mesh1306484637_1.geometry} material={materials.mat10} />
      <mesh geometry={nodes.mesh1306484637_2.geometry} material={materials.mat22} />
    </group>
  )
}

useGLTF.preload('./models/HPEInnovationHub.glb')
