/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/ProLiantVillage.glb 
*/

import React, { useLayoutEffect, useRef } from 'react'
import { useGLTF, useScroll } from '@react-three/drei'
import gsap from 'gsap';
import { useFrame } from '@react-three/fiber';

export function ProLiantVillage(props) {
  const { nodes, materials } = useGLTF('./models/ProLiantVillage.glb');

  const FLOOR_HEIGHT = 0.4;
  const NB_FLOORS = 3;

  const ref = useRef();
  const tl = useRef();

  const scroll = useScroll();

  useFrame(() => {
    tl.current.seek(scroll.offset * tl.current.duration());
  });

  useLayoutEffect(() => {
    tl.current = gsap.timeline();

    // rotation
    tl.current.to(
      ref.current.rotation,
      {
        duration: 3,
        y: Math.PI * 2 / 5,
      },
      0,
    );

    // position 1
    tl.current.to(
      ref.current.position,
      {
        duration: 1,
        y: -FLOOR_HEIGHT * (NB_FLOORS - 1),
        x: -2,
        z: 2
      },
      0,
    );

    // position 2
    tl.current.to(
      ref.current.position,
      {
        duration: 1.5,
        y: -FLOOR_HEIGHT * (NB_FLOORS - 1),
        x: 2,
        z: -2
      },
      1.5,
    );
  }, []);

  return (
    <group {...props} dispose={null} ref={ref} position={[1, 0, -2]} rotation={[0, -Math.PI * 1 / 4, 0]}>
      <mesh geometry={nodes.group2056379575.geometry} material={materials.mat22} />
      <mesh geometry={nodes.group414357712.geometry} material={materials.mat17} />
      <mesh geometry={nodes.group727847865.geometry} material={materials.mat13} />
      <mesh geometry={nodes.group1086968796.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group680713391.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group2062560926.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group1889838734.geometry} material={materials.mat12} />
      <mesh geometry={nodes.group691832941.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group88018646.geometry} material={materials.mat22} />
      <mesh geometry={nodes.group1413670021.geometry} material={materials.mat10} />
      <mesh geometry={nodes.group1292478617.geometry} material={materials.mat8} />
      <mesh geometry={nodes.group888813550.geometry} material={materials.mat10} />
      <mesh geometry={nodes.group750141131.geometry} material={materials.mat8} />
      <mesh geometry={nodes.group1609482893.geometry} material={materials.mat10} />
      <mesh geometry={nodes.group710396509.geometry} material={materials.mat8} />
      <mesh geometry={nodes.group1985881325.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group1406586557.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group586972705.geometry} material={materials.mat4} />
      <mesh geometry={nodes.group865637349.geometry} material={materials.mat4} />
      <mesh geometry={nodes.group1346688743.geometry} material={materials.mat4} />
      <mesh geometry={nodes.group15668877.geometry} material={materials.mat4} />
      <mesh geometry={nodes.group543029238.geometry} material={materials.mat8} />
      <mesh geometry={nodes.group1572810205.geometry} material={materials.mat8} />
      <mesh geometry={nodes.group1264051455.geometry} material={materials.mat8} />
      <mesh geometry={nodes.group1694619797.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group1874814520.geometry} material={materials.mat13} />
      <mesh geometry={nodes.group1864723542.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group2067440347.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group2080372011.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group172467855.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group1857028265.geometry} material={materials.mat13} />
      <mesh geometry={nodes.group733224695.geometry} material={materials.mat13} />
      <mesh geometry={nodes.group1998030372.geometry} material={materials.mat12} />
      <mesh geometry={nodes.group1639921841.geometry} material={materials.mat12} />
      <mesh geometry={nodes.group1498273787.geometry} material={materials.mat12} />
      <mesh geometry={nodes.group1776510033.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group1399863776.geometry} material={materials.mat12} />
      <mesh geometry={nodes.group1258426828.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group1865140274.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group475029708.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group1353696619.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group40712154.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group640296601.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group1418271139.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group522458781.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group467366901.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1323048669.geometry} material={materials.mat13} />
      <mesh geometry={nodes.group441506543.geometry} material={materials.mat8} />
      <mesh geometry={nodes.group524105105.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group1620878968.geometry} material={materials.mat8} />
      <mesh geometry={nodes.group1084844802.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group868537852.geometry} material={materials.mat13} />
      <mesh geometry={nodes.group516813704.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group101110207.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group2099187000.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1766597619.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1320926355.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group951137749.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group262444250.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group600335053.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1134130336.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group2038653779.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1587370546.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group651024463.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group665012737.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group60436686.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group221600017.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1695095144.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1532230904.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1181506897.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1927059894.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1946522784.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group2116089924.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group47558302.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group769597487.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1597569391.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group56515508.geometry} material={materials.mat3} />
      <mesh geometry={nodes.group2121824914.geometry} material={materials.mat8} />
      <mesh geometry={nodes.group1256814026.geometry} material={materials.mat10} />
      <mesh geometry={nodes.group1121734058.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group1143673223.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group85822852.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group1472696258.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group24584671.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group1003486860.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group150241968.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group1841617065.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group2012264116.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group508754903.geometry} material={materials.mat3} />
      <mesh geometry={nodes.group939338192.geometry} material={materials.mat3} />
      <mesh geometry={nodes.group1593054381.geometry} material={materials.mat13} />
      <mesh geometry={nodes.group359087187.geometry} material={materials.mat13} />
      <mesh geometry={nodes.group102774809.geometry} material={materials.mat13} />
      <mesh geometry={nodes.group2107722866.geometry} material={materials.mat13} />
      <mesh geometry={nodes.group1638089409.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group2142662702.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group797205382.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group60091006.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group750828229.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group200889301.geometry} material={materials.mat8} />
      <mesh geometry={nodes.group961430359.geometry} material={materials.mat8} />
      <mesh geometry={nodes.group698589884.geometry} material={materials.mat8} />
      <mesh geometry={nodes.group1479201752.geometry} material={materials.mat8} />
      <mesh geometry={nodes.group1528848347.geometry} material={materials.mat8} />
      <mesh geometry={nodes.group1526546155.geometry} material={materials.mat4} />
      <mesh geometry={nodes.group904729909.geometry} material={materials.mat4} />
      <mesh geometry={nodes.group609919743.geometry} material={materials.mat1} />
      <mesh geometry={nodes.group157386536.geometry} material={materials.mat1} />
      <mesh geometry={nodes.group795522403.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group1245600664.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group55739721.geometry} material={materials.mat13} />
      <mesh geometry={nodes.group624325729.geometry} material={materials.mat13} />
      <mesh geometry={nodes.group259297882.geometry} material={materials.mat5} />
      <mesh geometry={nodes.group911345688.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group562950462.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group1219566439.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group663642523.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group567964394.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group64923815.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group2141153155.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group122350609.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group1773794116.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group660944614.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group1185755869.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group1677070716.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group2147293245.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group1421193879.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group817846806.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1137983878.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1765287927.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group1864489442.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group1797051622.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group762748902.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group128466819.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group454942412.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group1028218531.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group618450094.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group1669668552.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group92377835.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group886828513.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group921285744.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group1686704755.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group477270091.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group798545587.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group2041132653.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group268677556.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group1082422202.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group1753874170.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group1738925954.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group797665846.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group1470642122.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group559594553.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group900634096.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group291881985.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1003508232.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group208655468.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group493694332.geometry} material={materials.mat18} />
      <mesh geometry={nodes.group124321088.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1070809099.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1257396414.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1391114563.geometry} material={materials.mat8} />
      <mesh geometry={nodes.group1464448322.geometry} material={materials.mat3} />
      <mesh geometry={nodes.group993735862.geometry} material={materials.mat3} />
      <mesh geometry={nodes.group684377666.geometry} material={materials.mat19} />
      <mesh geometry={nodes.group1631379365.geometry} material={materials.mat19} />
      <mesh geometry={nodes.group1428455456.geometry} material={materials.mat19} />
      <mesh geometry={nodes.group41957016.geometry} material={materials.mat19} />
      <mesh geometry={nodes.group1940431739.geometry} material={materials.mat19} />
      <mesh geometry={nodes.group1496653941.geometry} material={materials.mat19} />
      <mesh geometry={nodes.group385987102.geometry} material={materials.mat19} />
      <mesh geometry={nodes.group1911176560.geometry} material={materials.mat19} />
      <mesh geometry={nodes.group723952216.geometry} material={materials.mat19} />
      <mesh geometry={nodes.group1674529371.geometry} material={materials.mat19} />
      <mesh geometry={nodes.group500989838.geometry} material={materials.mat3} />
      <mesh geometry={nodes.group669578198.geometry} material={materials.mat3} />
      <mesh geometry={nodes.group304139486.geometry} material={materials.mat18} />
      <mesh geometry={nodes.group2037240451.geometry} material={materials.mat18} />
      <mesh geometry={nodes.group2085132497.geometry} material={materials.mat3} />
      <mesh geometry={nodes.group247945956.geometry} material={materials.mat3} />
      <mesh geometry={nodes.group1230207693.geometry} material={materials.mat3} />
      <mesh geometry={nodes.group2035227387.geometry} material={materials.mat3} />
      <mesh geometry={nodes.group844372103.geometry} material={materials.mat13} />
      <mesh geometry={nodes.group1164346816.geometry} material={materials.mat13} />
      <mesh geometry={nodes.group731115180.geometry} material={materials.mat13} />
      <mesh geometry={nodes.group2146013245.geometry} material={materials.mat13} />
      <mesh geometry={nodes.group1210557889.geometry} material={materials.mat13} />
      <mesh geometry={nodes.group1066419342.geometry} material={materials.mat13} />
      <mesh geometry={nodes.group1193964737.geometry} material={materials.mat13} />
      <mesh geometry={nodes.group993141604.geometry} material={materials.mat13} />
      <mesh geometry={nodes.group891167760.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group1664575033.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group845326814.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group1169640308.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group151959752.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group1314544456.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group1464424685.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group1880506347.geometry} material={materials.mat4} />
      <mesh geometry={nodes.group1573184345.geometry} material={materials.mat4} />
      <mesh geometry={nodes.group1568188021.geometry} material={materials.mat4} />
      <mesh geometry={nodes.group1787596049.geometry} material={materials.mat4} />
      <mesh geometry={nodes.group2047162039.geometry} material={materials.mat4} />
      <mesh geometry={nodes.group206528836.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group1880592623.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group1843916533.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group943336647.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group1951152715.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group2026192871.geometry} material={materials.mat0} />
      <mesh geometry={nodes.group547319172.geometry} material={materials.mat17} />
      <mesh geometry={nodes.group1830944184.geometry} material={materials.mat6} />
      <mesh geometry={nodes.group1744693932.geometry} material={materials.mat6} />
      <mesh geometry={nodes.group242284226.geometry} material={materials.mat17} />
      <mesh geometry={nodes.group1847397043.geometry} material={materials.mat17} />
      <mesh geometry={nodes.group14204489.geometry} material={materials.mat6} />
      <mesh geometry={nodes.group135234260.geometry} material={materials.mat3} />
      <mesh geometry={nodes.group1720634340.geometry} material={materials.mat6} />
      <mesh geometry={nodes.group523951915.geometry} material={materials.mat6} />
      <mesh geometry={nodes.group2099066497.geometry} material={materials.mat6} />
      <mesh geometry={nodes.group1383291985.geometry} material={materials.mat3} />
      <mesh geometry={nodes.group316979448.geometry} material={materials.mat17} />
      <mesh geometry={nodes.group337424666.geometry} material={materials.mat17} />
      <mesh geometry={nodes.group1703004556.geometry} material={materials.mat17} />
      <mesh geometry={nodes.group1325840211.geometry} material={materials.mat3} />
      <mesh geometry={nodes.group1127167855.geometry} material={materials.mat25} />
      <mesh geometry={nodes.group251944486.geometry} material={materials.mat6} />
      <mesh geometry={nodes.group314705383.geometry} material={materials.mat6} />
      <mesh geometry={nodes.group416838217.geometry} material={materials.mat6} />
      <mesh geometry={nodes.group1802874381.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group700093952.geometry} material={materials.mat13} />
      <mesh geometry={nodes.group1241103983.geometry} material={materials.mat13} />
      <mesh geometry={nodes.group1787663556.geometry} material={materials.mat13} />
      <mesh geometry={nodes.group55021070.geometry} material={materials.mat13} />
      <mesh geometry={nodes.group1100348246.geometry} material={materials.mat13} />
      <mesh geometry={nodes.group475936151.geometry} material={materials.mat13} />
      <mesh geometry={nodes.group1530364807.geometry} material={materials.mat13} />
      <mesh geometry={nodes.group1897230613.geometry} material={materials.mat13} />
      <mesh geometry={nodes.group1512008771.geometry} material={materials.mat13} />
      <mesh geometry={nodes.group992920988.geometry} material={materials.mat5} />
      <mesh geometry={nodes.group1465108883.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group1740676640.geometry} material={materials.mat13} />
      <mesh geometry={nodes.group1391233971.geometry} material={materials.mat17} />
      <mesh geometry={nodes.group1297668711.geometry} material={materials.mat3} />
      <mesh geometry={nodes.group620383973.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1177090369.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1860358994.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group878678446.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group506627292.geometry} material={materials.mat3} />
      <mesh geometry={nodes.group1814875046.geometry} material={materials.mat3} />
      <mesh geometry={nodes.group1030007046.geometry} material={materials.mat3} />
      <mesh geometry={nodes.group124364111.geometry} material={materials.mat3} />
      <mesh geometry={nodes.group728602477.geometry} material={materials.mat3} />
      <mesh geometry={nodes.group1957333004.geometry} material={materials.mat13} />
      <mesh geometry={nodes.group1720232977.geometry} material={materials.mat13} />
      <mesh geometry={nodes.group1975520359.geometry} material={materials.mat17} />
      <mesh geometry={nodes.group1453221850.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1402842132.geometry} material={materials.mat8} />
      <mesh geometry={nodes.group148017623.geometry} material={materials.mat8} />
      <mesh geometry={nodes.group2042011293.geometry} material={materials.mat8} />
      <mesh geometry={nodes.group1613865620.geometry} material={materials.mat13} />
      <mesh geometry={nodes.group1528223782.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group385348057.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group647559403.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group102274334.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group912519134.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group904430728.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group1674520274.geometry} material={materials.mat5} />
      <mesh geometry={nodes.group1579184403.geometry} material={materials.mat5} />
      <mesh geometry={nodes.group930640138.geometry} material={materials.mat5} />
      <mesh geometry={nodes.group1615729652.geometry} material={materials.mat5} />
      <mesh geometry={nodes.group974648111.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group573343453.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group1883979655.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group1597084126.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1053331229.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group1752120256.geometry} material={materials.mat2} />
      <mesh geometry={nodes.group390122617.geometry} material={materials.mat2} />
      <mesh geometry={nodes.group1194867214.geometry} material={materials.mat2} />
      <mesh geometry={nodes.group1237680604.geometry} material={materials.mat2} />
      <mesh geometry={nodes.group308760357.geometry} material={materials.mat18} />
      <mesh geometry={nodes.group39295081.geometry} material={materials.mat18} />
      <mesh geometry={nodes.group595557110.geometry} material={materials.mat18} />
      <mesh geometry={nodes.group963697911.geometry} material={materials.mat18} />
      <mesh geometry={nodes.group469996019.geometry} material={materials.mat18} />
      <mesh geometry={nodes.group219103445.geometry} material={materials.mat18} />
      <mesh geometry={nodes.group306285786.geometry} material={materials.mat18} />
      <mesh geometry={nodes.group1909001179.geometry} material={materials.mat18} />
      <mesh geometry={nodes.group402650929.geometry} material={materials.mat18} />
      <mesh geometry={nodes.group1503235509.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group642123494.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group1643420536.geometry} material={materials.mat2} />
      <mesh geometry={nodes.group759333935.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group1833379398.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group1219882469.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group545945156.geometry} material={materials.mat19} />
      <mesh geometry={nodes.group900368980.geometry} material={materials.mat3} />
      <mesh geometry={nodes.group781204852.geometry} material={materials.mat3} />
      <mesh geometry={nodes.group866268704.geometry} material={materials.mat3} />
      <mesh geometry={nodes.group228676126.geometry} material={materials.mat3} />
      <mesh geometry={nodes.group952569421.geometry} material={materials.mat3} />
      <mesh geometry={nodes.group1332691708.geometry} material={materials.mat3} />
      <mesh geometry={nodes.group1978864617.geometry} material={materials.mat3} />
      <mesh geometry={nodes.group332407064.geometry} material={materials.mat3} />
      <mesh geometry={nodes.group1714672003.geometry} material={materials.mat3} />
      <mesh geometry={nodes.group902987557.geometry} material={materials.mat3} />
      <mesh geometry={nodes.group189065125.geometry} material={materials.mat3} />
      <mesh geometry={nodes.group856587613.geometry} material={materials.mat3} />
      <mesh geometry={nodes.group1367033778.geometry} material={materials.mat3} />
      <mesh geometry={nodes.group1932401182.geometry} material={materials.mat3} />
      <mesh geometry={nodes.group1092813159.geometry} material={materials.mat8} />
      <mesh geometry={nodes.group90905418.geometry} material={materials.mat8} />
      <mesh geometry={nodes.group1071661591.geometry} material={materials.mat8} />
      <mesh geometry={nodes.group1738441144.geometry} material={materials.mat8} />
      <mesh geometry={nodes.group1540958086.geometry} material={materials.mat8} />
      <mesh geometry={nodes.group1499286270.geometry} material={materials.mat8} />
      <mesh geometry={nodes.group1523448264.geometry} material={materials.mat8} />
      <mesh geometry={nodes.group1604598374.geometry} material={materials.mat8} />
      <mesh geometry={nodes.group1188263133.geometry} material={materials.mat8} />
      <mesh geometry={nodes.group774631724.geometry} material={materials.mat8} />
      <mesh geometry={nodes.group56013104.geometry} material={materials.mat8} />
      <mesh geometry={nodes.group178770645.geometry} material={materials.mat8} />
      <mesh geometry={nodes.group1141888760.geometry} material={materials.mat8} />
      <mesh geometry={nodes.group1806273415.geometry} material={materials.mat8} />
      <mesh geometry={nodes.group1348765653.geometry} material={materials.mat8} />
      <mesh geometry={nodes.group651857968.geometry} material={materials.mat8} />
      <mesh geometry={nodes.group1880427034.geometry} material={materials.mat8} />
      <mesh geometry={nodes.group1766949960.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group23998760.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group257320616.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group840381656.geometry} material={materials.mat13} />
      <mesh geometry={nodes.group620316437.geometry} material={materials.mat13} />
      <mesh geometry={nodes.group865222195.geometry} material={materials.mat13} />
      <mesh geometry={nodes.group730837410.geometry} material={materials.mat6} />
      <mesh geometry={nodes.group1027791352.geometry} material={materials.mat6} />
      <mesh geometry={nodes.group307989858.geometry} material={materials.mat6} />
      <mesh geometry={nodes.group1144655713.geometry} material={materials.mat6} />
      <mesh geometry={nodes.group2009595080.geometry} material={materials.mat6} />
      <mesh geometry={nodes.group1756705620.geometry} material={materials.mat6} />
      <mesh geometry={nodes.group1581661086.geometry} material={materials.mat6} />
      <mesh geometry={nodes.group484370377.geometry} material={materials.mat6} />
      <mesh geometry={nodes.group1714945889.geometry} material={materials.mat6} />
      <mesh geometry={nodes.group1497521080.geometry} material={materials.mat6} />
      <mesh geometry={nodes.group1108635992.geometry} material={materials.mat6} />
      <mesh geometry={nodes.group1469021680.geometry} material={materials.mat6} />
      <mesh geometry={nodes.group1473708752.geometry} material={materials.mat6} />
      <mesh geometry={nodes.group1207470232.geometry} material={materials.mat6} />
      <mesh geometry={nodes.group266128581.geometry} material={materials.mat6} />
      <mesh geometry={nodes.group220053028.geometry} material={materials.mat6} />
      <mesh geometry={nodes.group716105814.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group1593613913.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group1222437788.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group2132910191.geometry} material={materials.mat3} />
      <mesh geometry={nodes.group85898500.geometry} material={materials.mat3} />
      <mesh geometry={nodes.group86393190.geometry} material={materials.mat12} />
      <mesh geometry={nodes.group1382287371.geometry} material={materials.mat12} />
      <mesh geometry={nodes.group1439635812.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group941049133.geometry} material={materials.mat10} />
      <mesh geometry={nodes.group163031802.geometry} material={materials.mat10} />
      <mesh geometry={nodes.group1679570353.geometry} material={materials.mat10} />
      <mesh geometry={nodes.group946209829.geometry} material={materials.mat10} />
      <mesh geometry={nodes.group1403162245.geometry} material={materials.mat10} />
      <mesh geometry={nodes.group1777963046.geometry} material={materials.mat10} />
      <mesh geometry={nodes.group2069658298.geometry} material={materials.mat10} />
      <mesh geometry={nodes.group890088657.geometry} material={materials.mat10} />
      <mesh geometry={nodes.group1091540372.geometry} material={materials.mat2} />
      <mesh geometry={nodes.group204137803.geometry} material={materials.mat2} />
      <mesh geometry={nodes.group2022482304.geometry} material={materials.mat2} />
      <mesh geometry={nodes.group1578200380.geometry} material={materials.mat2} />
      <mesh geometry={nodes.group238242423.geometry} material={materials.mat2} />
      <mesh geometry={nodes.group1742656630.geometry} material={materials.mat2} />
      <mesh geometry={nodes.group487077061.geometry} material={materials.mat2} />
      <mesh geometry={nodes.group2048561999.geometry} material={materials.mat6} />
      <mesh geometry={nodes.group307702733.geometry} material={materials.mat6} />
      <mesh geometry={nodes.group22780939.geometry} material={materials.mat6} />
      <mesh geometry={nodes.group1476163393.geometry} material={materials.mat6} />
      <mesh geometry={nodes.group99640494.geometry} material={materials.mat6} />
      <mesh geometry={nodes.group1338579614.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group1341945882.geometry} material={materials.mat13} />
      <mesh geometry={nodes.group2001963217.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1454617081.geometry} material={materials.mat12} />
      <mesh geometry={nodes.group565449673.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group618592561.geometry} material={materials.mat13} />
      <mesh geometry={nodes.group1551347828.geometry} material={materials.mat19} />
      <mesh geometry={nodes.group1243373000.geometry} material={materials.mat19} />
      <mesh geometry={nodes.group1780659953.geometry} material={materials.mat19} />
      <mesh geometry={nodes.group2037377278.geometry} material={materials.mat19} />
      <mesh geometry={nodes.mesh1620407527.geometry} material={materials.mat17} />
      <mesh geometry={nodes.mesh1620407527_1.geometry} material={materials.mat9} />
      <mesh geometry={nodes.mesh1620407527_2.geometry} material={materials.mat19} />
      <mesh geometry={nodes.mesh1620407527_3.geometry} material={materials.mat16} />
      <mesh geometry={nodes.mesh1620407527_4.geometry} material={materials.mat20} />
      <mesh geometry={nodes.mesh932878423.geometry} material={materials.mat7} />
      <mesh geometry={nodes.mesh932878423_1.geometry} material={materials.mat20} />
      <mesh geometry={nodes.mesh932878423_2.geometry} material={materials.mat3} />
      <mesh geometry={nodes.mesh932878423_3.geometry} material={materials.mat8} />
      <mesh geometry={nodes.mesh126351928.geometry} material={materials.mat13} />
      <mesh geometry={nodes.mesh126351928_1.geometry} material={materials.mat3} />
      <mesh geometry={nodes.mesh126351928_2.geometry} material={materials.mat2} />
      <mesh geometry={nodes.mesh2099700118.geometry} material={materials.mat7} />
      <mesh geometry={nodes.mesh2099700118_1.geometry} material={materials.mat22} />
      <mesh geometry={nodes.mesh226365589.geometry} material={materials.mat22} />
      <mesh geometry={nodes.mesh226365589_1.geometry} material={materials.mat2} />
      <mesh geometry={nodes.mesh470365829.geometry} material={materials.mat6} />
      <mesh geometry={nodes.mesh470365829_1.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh470365829_2.geometry} material={materials.mat20} />
      <mesh geometry={nodes.mesh470365829_3.geometry} material={materials.mat3} />
      <mesh geometry={nodes.mesh442762496.geometry} material={materials.mat19} />
      <mesh geometry={nodes.mesh442762496_1.geometry} material={materials.mat14} />
      <mesh geometry={nodes.mesh1892910826.geometry} material={materials.mat15} />
      <mesh geometry={nodes.mesh1892910826_1.geometry} material={materials.mat3} />
      <mesh geometry={nodes.mesh1501873170.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh1501873170_1.geometry} material={materials.mat10} />
      <mesh geometry={nodes.mesh1501873170_2.geometry} material={materials.mat9} />
      <mesh geometry={nodes.mesh1501873170_3.geometry} material={materials.mat8} />
      <mesh geometry={nodes.mesh1082111208.geometry} material={materials.mat22} />
      <mesh geometry={nodes.mesh1082111208_1.geometry} material={materials.mat20} />
      <mesh geometry={nodes.mesh908718868.geometry} material={materials.mat20} />
      <mesh geometry={nodes.mesh908718868_1.geometry} material={materials.mat22} />
      <mesh geometry={nodes.mesh2065613719.geometry} material={materials.mat20} />
      <mesh geometry={nodes.mesh2065613719_1.geometry} material={materials.mat22} />
      <mesh geometry={nodes.mesh984693493.geometry} material={materials.mat20} />
      <mesh geometry={nodes.mesh984693493_1.geometry} material={materials.mat22} />
      <mesh geometry={nodes.mesh1748987001.geometry} material={materials.mat20} />
      <mesh geometry={nodes.mesh1748987001_1.geometry} material={materials.mat22} />
      <mesh geometry={nodes.mesh1680882446.geometry} material={materials.mat20} />
      <mesh geometry={nodes.mesh1680882446_1.geometry} material={materials.mat22} />
      <mesh geometry={nodes.mesh1680882446_2.geometry} material={materials.mat3} />
      <mesh geometry={nodes.mesh1106848498.geometry} material={materials.mat0} />
      <mesh geometry={nodes.mesh1106848498_1.geometry} material={materials.mat20} />
      <mesh geometry={nodes.mesh1780499532.geometry} material={materials.mat16} />
      <mesh geometry={nodes.mesh1780499532_1.geometry} material={materials.mat9} />
      <mesh geometry={nodes.mesh1937543949.geometry} material={materials.mat16} />
      <mesh geometry={nodes.mesh1937543949_1.geometry} material={materials.mat7} />
      <mesh geometry={nodes.mesh1124096706.geometry} material={materials.mat16} />
      <mesh geometry={nodes.mesh1124096706_1.geometry} material={materials.mat13} />
      <mesh geometry={nodes.mesh1971168243.geometry} material={materials.mat9} />
      <mesh geometry={nodes.mesh1971168243_1.geometry} material={materials.mat19} />
      <mesh geometry={nodes.mesh42259831.geometry} material={materials.mat19} />
      <mesh geometry={nodes.mesh42259831_1.geometry} material={materials.mat9} />
      <mesh geometry={nodes.mesh312989640.geometry} material={materials.mat14} />
      <mesh geometry={nodes.mesh312989640_1.geometry} material={materials.mat3} />
      <mesh geometry={nodes.mesh1122170750.geometry} material={materials.mat4} />
      <mesh geometry={nodes.mesh1122170750_1.geometry} material={materials.mat2} />
      <mesh geometry={nodes.mesh1122170750_2.geometry} material={materials.mat18} />
      <mesh geometry={nodes.mesh1122170750_3.geometry} material={materials.mat3} />
      <mesh geometry={nodes.mesh1942059648.geometry} material={materials.mat7} />
      <mesh geometry={nodes.mesh1942059648_1.geometry} material={materials.mat15} />
      <mesh geometry={nodes.mesh314485410.geometry} material={materials.mat6} />
      <mesh geometry={nodes.mesh314485410_1.geometry} material={materials.mat20} />
      <mesh geometry={nodes.mesh351618862.geometry} material={materials.mat6} />
      <mesh geometry={nodes.mesh351618862_1.geometry} material={materials.mat18} />
      <mesh geometry={nodes.mesh1127063720.geometry} material={materials.mat18} />
      <mesh geometry={nodes.mesh1127063720_1.geometry} material={materials.mat6} />
      <mesh geometry={nodes.mesh1754984776.geometry} material={materials.mat5} />
      <mesh geometry={nodes.mesh1754984776_1.geometry} material={materials.mat14} />
      <mesh geometry={nodes.mesh1754984776_2.geometry} material={materials.mat19} />
      <mesh geometry={nodes.mesh1597240921.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh1597240921_1.geometry} material={materials.mat10} />
      <mesh geometry={nodes.mesh1597240921_2.geometry} material={materials.mat9} />
      <mesh geometry={nodes.mesh2015324951.geometry} material={materials.mat9} />
      <mesh geometry={nodes.mesh2015324951_1.geometry} material={materials.mat17} />
      <mesh geometry={nodes.mesh676558152.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh676558152_1.geometry} material={materials.mat6} />
      <mesh geometry={nodes.mesh676558152_2.geometry} material={materials.mat16} />
      <mesh geometry={nodes.mesh1569413968.geometry} material={materials.mat10} />
      <mesh geometry={nodes.mesh1569413968_1.geometry} material={materials.mat13} />
      <mesh geometry={nodes.mesh1569413968_2.geometry} material={materials.mat4} />
      <mesh geometry={nodes.mesh1641489903.geometry} material={materials.mat8} />
      <mesh geometry={nodes.mesh1641489903_1.geometry} material={materials.mat3} />
      <mesh geometry={nodes.mesh1581773443.geometry} material={materials.mat3} />
      <mesh geometry={nodes.mesh1581773443_1.geometry} material={materials.mat8} />
      <mesh geometry={nodes.mesh1462187575.geometry} material={materials.mat3} />
      <mesh geometry={nodes.mesh1462187575_1.geometry} material={materials.mat8} />
      <mesh geometry={nodes.mesh2033216695.geometry} material={materials.mat7} />
      <mesh geometry={nodes.mesh2033216695_1.geometry} material={materials.mat15} />
      <mesh geometry={nodes.mesh872839425.geometry} material={materials.mat15} />
      <mesh geometry={nodes.mesh872839425_1.geometry} material={materials.mat7} />
      <mesh geometry={nodes.mesh1513056428.geometry} material={materials.mat15} />
      <mesh geometry={nodes.mesh1513056428_1.geometry} material={materials.mat7} />
      <mesh geometry={nodes.mesh2107200194.geometry} material={materials.mat15} />
      <mesh geometry={nodes.mesh2107200194_1.geometry} material={materials.mat7} />
      <mesh geometry={nodes.mesh842773834.geometry} material={materials.mat15} />
      <mesh geometry={nodes.mesh842773834_1.geometry} material={materials.mat7} />
      <mesh geometry={nodes.mesh935951105.geometry} material={materials.mat6} />
      <mesh geometry={nodes.mesh935951105_1.geometry} material={materials.mat3} />
      <mesh geometry={nodes.mesh880128162.geometry} material={materials.mat13} />
      <mesh geometry={nodes.mesh880128162_1.geometry} material={materials.mat11} />
      <mesh geometry={nodes.mesh880128162_2.geometry} material={materials.mat22} />
      <mesh geometry={nodes.mesh1571301754.geometry} material={materials.mat22} />
      <mesh geometry={nodes.mesh1571301754_1.geometry} material={materials.mat11} />
      <mesh geometry={nodes.mesh1452230727.geometry} material={materials.mat22} />
      <mesh geometry={nodes.mesh1452230727_1.geometry} material={materials.mat13} />
      <mesh geometry={nodes.mesh1452230727_2.geometry} material={materials.mat11} />
      <mesh geometry={nodes.mesh970764617.geometry} material={materials.mat9} />
      <mesh geometry={nodes.mesh970764617_1.geometry} material={materials.mat13} />
      <mesh geometry={nodes.mesh1103955063.geometry} material={materials.mat13} />
      <mesh geometry={nodes.mesh1103955063_1.geometry} material={materials.mat9} />
      <mesh geometry={nodes.mesh234630948.geometry} material={materials.mat13} />
      <mesh geometry={nodes.mesh234630948_1.geometry} material={materials.mat9} />
      <mesh geometry={nodes.mesh860925790.geometry} material={materials.mat13} />
      <mesh geometry={nodes.mesh860925790_1.geometry} material={materials.mat9} />
      <mesh geometry={nodes.mesh2062267188.geometry} material={materials.mat5} />
      <mesh geometry={nodes.mesh2062267188_1.geometry} material={materials.mat15} />
      <mesh geometry={nodes.mesh395040991.geometry} material={materials.mat5} />
      <mesh geometry={nodes.mesh395040991_1.geometry} material={materials.mat1} />
      <mesh geometry={nodes.mesh1856870417.geometry} material={materials.mat5} />
      <mesh geometry={nodes.mesh1856870417_1.geometry} material={materials.mat7} />
      <mesh geometry={nodes.mesh1742115893.geometry} material={materials.mat5} />
      <mesh geometry={nodes.mesh1742115893_1.geometry} material={materials.mat10} />
      <mesh geometry={nodes.mesh1955694657.geometry} material={materials.mat5} />
      <mesh geometry={nodes.mesh1955694657_1.geometry} material={materials.mat11} />
      <mesh geometry={nodes.mesh568651757.geometry} material={materials.mat5} />
      <mesh geometry={nodes.mesh568651757_1.geometry} material={materials.mat3} />
      <mesh geometry={nodes.mesh1823463482.geometry} material={materials.mat5} />
      <mesh geometry={nodes.mesh1823463482_1.geometry} material={materials.mat19} />
      <mesh geometry={nodes.mesh1103235028.geometry} material={materials.mat5} />
      <mesh geometry={nodes.mesh1103235028_1.geometry} material={materials.mat13} />
      <mesh geometry={nodes.mesh1635959395.geometry} material={materials.mat5} />
      <mesh geometry={nodes.mesh1635959395_1.geometry} material={materials.mat9} />
      <mesh geometry={nodes.mesh1536213894.geometry} material={materials.mat5} />
      <mesh geometry={nodes.mesh1536213894_1.geometry} material={materials.mat14} />
      <mesh geometry={nodes.mesh461107475.geometry} material={materials.mat5} />
      <mesh geometry={nodes.mesh461107475_1.geometry} material={materials.mat1} />
      <mesh geometry={nodes.mesh534372791.geometry} material={materials.mat5} />
      <mesh geometry={nodes.mesh534372791_1.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh1675421008.geometry} material={materials.mat16} />
      <mesh geometry={nodes.mesh1675421008_1.geometry} material={materials.mat20} />
      <mesh geometry={nodes.mesh1837669520.geometry} material={materials.mat20} />
      <mesh geometry={nodes.mesh1837669520_1.geometry} material={materials.mat16} />
    </group>
  )
}

useGLTF.preload('./models/ProLiantVillage.glb')
