/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/SimplivitySprings.glb 
*/

import React, { useLayoutEffect, useRef } from 'react'
import { useGLTF, useScroll } from '@react-three/drei'
import gsap from 'gsap';
import { useFrame } from '@react-three/fiber';

export function SimplivitySprings(props) {
  const { nodes, materials } = useGLTF('./models/SimplivitySprings.glb');

  const FLOOR_HEIGHT = 0.1;
  const NB_FLOORS = 3;

  const ref = useRef();
  const tl = useRef();

  const scroll = useScroll();

  useFrame(() => {
    tl.current.seek(scroll.offset * tl.current.duration());
  });

  useLayoutEffect(() => {
    tl.current = gsap.timeline();

    // rotation
    tl.current.to(
      ref.current.rotation,
      {
        duration: 3,
        y: -Math.PI,
      },
      0,
    );

    // position 1
    tl.current.to(
      ref.current.position,
      {
        duration: 1,
        y: -FLOOR_HEIGHT * (NB_FLOORS - 1),
        x: -2,
        z: 1
      },
      0,
    );

    // position 2
    tl.current.to(
      ref.current.position,
      {
        duration: 1,
        y: -FLOOR_HEIGHT * (NB_FLOORS - 1),
        x: 1.8,
        z: -3
      },
      1.5,
    );
  }, []);

  return (
    <group {...props} dispose={null} ref={ref} position={[1, 0, -2]}>
      <mesh geometry={nodes.group515955327.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1633543551.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group2111085806.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1214037127.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group939521850.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group1068991843.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group1663665451.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group1055656515.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group788564142.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group1026424589.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group885813434.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group1706336911.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group105374561.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1745070574.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1198312290.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group1713474330.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group1956289337.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group814106760.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group1905549968.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group274661053.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group545318518.geometry} material={materials.mat17} />
      <mesh geometry={nodes.group1642186014.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group305402846.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group1719820621.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1639225347.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group60303047.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group997002722.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group1339141532.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group966876486.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group1748900321.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group143380342.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group185026894.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group649507194.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group2055526671.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1751905527.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group1941157088.geometry} material={materials.mat6} />
      <mesh geometry={nodes.group1245740617.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group309578165.geometry} material={materials.mat6} />
      <mesh geometry={nodes.group700786540.geometry} material={materials.mat6} />
      <mesh geometry={nodes.group1118381565.geometry} material={materials.mat6} />
      <mesh geometry={nodes.group1669922238.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group2115780157.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group521253435.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1674516757.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group281106172.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group448530868.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group1799461775.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group480987612.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group1242777026.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group857185059.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group1049643027.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group1816251414.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group151130468.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group2035313559.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1395838570.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group1769393804.geometry} material={materials.mat6} />
      <mesh geometry={nodes.group396095085.geometry} material={materials.mat6} />
      <mesh geometry={nodes.group1832753327.geometry} material={materials.mat17} />
      <mesh geometry={nodes.group211415205.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group1404941618.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group805161109.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group1554027304.geometry} material={materials.mat17} />
      <mesh geometry={nodes.group1940829662.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group42792756.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group695566114.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1658869409.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1498790883.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1567973880.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group2112816566.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group236026478.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group506122320.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group422174421.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group234085444.geometry} material={materials.mat6} />
      <mesh geometry={nodes.group1581203494.geometry} material={materials.mat6} />
      <mesh geometry={nodes.group1910645407.geometry} material={materials.mat4} />
      <mesh geometry={nodes.group639082576.geometry} material={materials.mat4} />
      <mesh geometry={nodes.group809081644.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group487656746.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group2048468232.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group803119716.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1478378586.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1778629953.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group36499224.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1357013777.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group874347315.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group959547400.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group318662595.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1926023225.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group248919914.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1996459835.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1153867881.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1976371976.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1251332224.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group796899191.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1372360505.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1201117627.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1213041136.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1120812832.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group10317084.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group877587065.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group972644260.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1681416619.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group466627879.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group348268234.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1324853398.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1891223359.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1489040052.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group273703032.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1151267849.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1494380295.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1923294432.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group2137107079.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1517466184.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1274729968.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group392165265.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1000780686.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group558857069.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group676204893.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1635666140.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group969464947.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group711099680.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group760212485.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group311192550.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1757553328.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1075823972.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1275148672.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group336491837.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1130110352.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group453776555.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group292759512.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group2015457372.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group244096700.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group400690331.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1789941349.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group290357085.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1426938614.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1285360155.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group393655396.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1665179426.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1641262543.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1868558866.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group97211833.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group864625790.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group82930784.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group667036277.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1865041219.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1009613340.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group728547560.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1720648961.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group313756121.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group245597090.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1126367389.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1538454307.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group1701983358.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group347276412.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group126413088.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group594021031.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group2087216161.geometry} material={materials.mat17} />
      <mesh geometry={nodes.group1484187692.geometry} material={materials.mat17} />
      <mesh geometry={nodes.group364329972.geometry} material={materials.mat17} />
      <mesh geometry={nodes.group12599840.geometry} material={materials.mat17} />
      <mesh geometry={nodes.group1002731857.geometry} material={materials.mat17} />
      <mesh geometry={nodes.group1231666297.geometry} material={materials.mat17} />
      <mesh geometry={nodes.group1472796802.geometry} material={materials.mat17} />
      <mesh geometry={nodes.group1149333663.geometry} material={materials.mat17} />
      <mesh geometry={nodes.group655620411.geometry} material={materials.mat17} />
      <mesh geometry={nodes.group816287160.geometry} material={materials.mat17} />
      <mesh geometry={nodes.group816586694.geometry} material={materials.mat17} />
      <mesh geometry={nodes.group117590204.geometry} material={materials.mat17} />
      <mesh geometry={nodes.group1321781349.geometry} material={materials.mat6} />
      <mesh geometry={nodes.group429282351.geometry} material={materials.mat6} />
      <mesh geometry={nodes.group1546686745.geometry} material={materials.mat6} />
      <mesh geometry={nodes.group1183465.geometry} material={materials.mat6} />
      <mesh geometry={nodes.group523681241.geometry} material={materials.mat6} />
      <mesh geometry={nodes.group875314098.geometry} material={materials.mat6} />
      <mesh geometry={nodes.group398114424.geometry} material={materials.mat6} />
      <mesh geometry={nodes.group619492068.geometry} material={materials.mat6} />
      <mesh geometry={nodes.group1033656833.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group2028282286.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group582622182.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group973498868.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group1339627111.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group890098876.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group627147727.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group561816923.geometry} material={materials.mat16} />
    </group>
  )
}

useGLTF.preload('./models/SimplivitySprings.glb')
